# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
      
    steps:
     - name: SSH Execute Commands
    # You may pin to the exact commit or the version.
    # uses: JimCronqvist/action-ssh@1c03e01b4ac39da814b45cfd2924c2df0ff1396f
    uses: JimCronqvist/action-ssh@0.1.1
    with:
      # Command(s) to execute on the remote server.
      command: cd ${{ secrets.PATH }}; sh deploy.sh
      # Hostname or IP address of the remote server(s). Separate multiple servers with a blank space. Example: 'user@mydomain.com:22 user@otherdomain.com:2222'
      hosts: ${{ secrets.USER }}@${{ secrets.HOST }}
      # The private key (id_rsa) content for authenticating to the SSH server(s). Recommended to store it as a GitHub Secret.
      privateKey: ${{ secrets.KEY}}
      # Used to view all environment variables in the logs, please note that this could expose sensitive data.

